import { describe, expect, it, vi } from "vitest";
import { VoiceController, VoiceService } from "../src/chat/voice";
function actions() { return {voiceStart:vi.fn(async()=>{}),voiceStop:vi.fn(async()=>"Merhaba"),voiceCancel:vi.fn(async()=>{}),voiceSpeak:vi.fn(async()=>{}),voiceSilence:vi.fn(async()=>{}),voiceSupported:vi.fn(async()=>({whisper:true,winrt_stt:false,tts:true}))}; }
describe("Yerel ses",()=>{
 it("hızlı bırakma tek kayıt açar ve metni incelemeye bırakır",async()=>{ const a=actions(); const c=new VoiceController(a); const press=c.press(); const release=c.release(); await Promise.all([press,release]); expect(a.voiceStart).toHaveBeenCalledOnce(); expect(a.voiceStop).toHaveBeenCalledOnce(); expect(c.transcript).toBe("Merhaba"); expect(c.micOpen).toBe(false); });
 it("iptal açılmakta olan mikrofonu da kapatır",async()=>{ const a=actions(); let done!:()=>void; a.voiceStart.mockImplementation(()=>new Promise<void>(r=>done=r)); const c=new VoiceController(a); const pending=c.press(); const cancel=c.cancel(); done(); await Promise.all([pending,cancel]); expect(a.voiceCancel).toHaveBeenCalledTimes(2); expect(a.voiceStop).not.toHaveBeenCalled(); expect(c.micOpen).toBe(false); });
 it("eksik modelde ikinci bir kayıt başlatmaz",async()=>{ const a=actions(); a.voiceStop.mockRejectedValue(new Error("model")); const c=new VoiceController(a); await c.press(); await c.release(); expect(a.voiceStart).toHaveBeenCalledOnce(); expect(c.message).toContain("yazarak"); expect(c.message).toContain("modeli"); });
 it("ses varsayılan kapalı, bilinmeyen durumda sessiz, olay bir kez",async()=>{const a=actions();const s=new VoiceService(a);const e={kind:"JOB_FINISHED" as const,taskId:"j",agent:"codex" as const}; await s.announce(e,true,1); expect(a.voiceSpeak).not.toHaveBeenCalled(); s.enabled=true;await s.announce(e,false,2);expect(a.voiceSpeak).not.toHaveBeenCalled();await s.announce(e,true,3);await s.announce(e,true,40000);expect(a.voiceSpeak).toHaveBeenCalledOnce(); });
});

it("iptal devam ederken yeni press kaydı yeniden açmaz",async()=>{const a=actions();const c=new VoiceController(a);const cancelling=c.cancel();const pressing=c.press();await Promise.all([cancelling,pressing]);expect(a.voiceStart).not.toHaveBeenCalled();expect(c.micOpen).toBe(false);});
it("iptal edilmiş çözümlemenin mesajı sonradan görünmez",async()=>{const a=actions();let done!:(s:string)=>void;a.voiceStop.mockImplementation(()=>new Promise<string>(r=>done=r));const changed=vi.fn();const c=new VoiceController(a,changed);await c.press();const release=c.release();await Promise.resolve();const cancelling=c.cancel();done("eski ses");await Promise.all([release,cancelling]);expect(c.transcript).toBe("");expect(c.message).toBe("");expect(c.state).toBe("idle");});
it("başlangıç iptali mikrofon açılışını beklemeden arka uca iletilir",async()=>{const a=actions();let finish!:()=>void;a.voiceStart.mockImplementation(()=>new Promise<void>(r=>finish=r));const c=new VoiceController(a);const start=c.press();const cancel=c.cancel();expect(a.voiceCancel).toHaveBeenCalledOnce();finish();await Promise.all([start,cancel]);expect(c.micOpen).toBe(false);expect(c.state).toBe("idle");expect(a.voiceCancel).toHaveBeenCalledTimes(2);});

it.each(["Windows konuşma tanıma hazır değil; mesajını yazarak gönder.","Windows konuşma tanıma izni kapalı; Windows ayarlarından açıp tekrar dene.","Windows konuşma tanıma internete bağlanamadı; bağlantını kontrol edip tekrar dene."])("Windows başlangıç hatası güvenli açıklanır: %s",async(message)=>{const a=actions();a.voiceStart.mockRejectedValue(new Error(message));const c=new VoiceController(a);await c.press();expect(c.message).toBe(message);expect(c.micOpen).toBe(false);});
it("iptal edilen Windows başlangıcı eski ağ hatasını göstermez",async()=>{const a=actions();let reject!:(e:Error)=>void;a.voiceStart.mockImplementation(()=>new Promise<void>((_,r)=>reject=r));const c=new VoiceController(a);const start=c.press();const cancel=c.cancel();reject(new Error("Windows konuşma tanıma internete bağlanamadı; bağlantını kontrol edip tekrar dene."));await Promise.all([start,cancel]);expect(c.message).toBe("");expect(c.micOpen).toBe(false);});
