"""Current 77-feature inventory contracts. Recovery remaps the historical
70 entries by feature identity; required source tokens remain unchanged.
Runtime evidence references do not imply a fresh Windows test execution.
"""
import re

def source_contract_contains(source, token):
    # CSS spaces do not change the value: keep the exact 1.03 requirement.
    if token == "--pet-brightness:1.03":
        return bool(re.search(r"--pet-brightness\s*:\s*1\.03\s*;", source))
    return token in source

CONTRACTS = {1: ('windows/src/views/views.ts', ['health-strip', 'pill("AfuNöbet"', 'pill("GPT"'], 'aktivasyon_kontrol.test.ts'),
 2: ('windows/src/core/state.ts', ['pendingOrkestra', 'setPendingOrkestra'], 'aktivasyon_kontrol.test.ts'),
 3: ('windows/src/afu/character.ts',
     ['ANIM_HARITASI', 'calisma_yazma.webp', 'onay_bekleme.webp'],
     'tum_ozellik_etkilesim.test.ts'),
 4: ('windows/src/style.css',
     ['--pet-brightness:1.03', 'data-durum="calisiyor"', '--pet-filtre', 'var(--pet-arka'],
     'working-100.png'),
 5: ('windows/src-tauri/src/apps.rs', ['github.com/pirncedark', 'indir'], 'apps.test.ts'),
 6: ('.github/workflows/ci.yml',
     ['pull_request:', 'tsc --noEmit', 'cargo test', 'python -m pytest -q tests'],
     'test_tum_ozellik_sozlesme.py'),
 7: ('windows/src/core/state.ts', ['STALE_MS', 'isCurrent', 'updatedAt'], 'state.test.ts'),
 8: ('windows/src/views/views.ts', ['main-task', 'taskMessage', 'elapsedText'], 'arayuz.test.ts'),
 9: ('windows/src/core/state.ts', ['currentAction', 'taskMessage'], 'state.test.ts'),
 10: ('windows/src/views/model.ts', ['triage', 'split', 'verify', 'stageSteps'], 'tum_ozellik_gorev.test.ts'),
 11: ('windows/src-tauri/src/watch.rs', ['notify', 'idle_watch_never_produces_a_timer_read'], 'cargo.log'),
 12: ('windows/src/views/model.ts', ['agentPills', 'agentPillState'], 'tum_ozellik_etkilesim.test.ts'),
 13: ('windows/src/core/state.ts', ['quotaRows', 'remaining_percent'], 'state.test.ts'),
 14: ('windows/src-tauri/src/orkestra.rs', ['orkestra_send', 'CREATE_NO_WINDOW'], 'test_tum_ozellik_sozlesme.py'),
 15: ('windows/src/views/model.ts', ['modelText', 'effort'], 'tum_ozellik_gorev.test.ts'),
 16: ('windows/src/views/model.ts', ['contextText', 'cached', 'saved'], 'tum_ozellik_gorev.test.ts'),
 17: ('windows/src/views/model.ts', ['costText', 'toFixed(2)'], 'tum_ozellik_gorev.test.ts'),
 18: ('windows/src/views/views.ts', ['claude-lock', 'KORUNUYOR'], 'f1_f5.test.ts'),
 19: ('windows/src/afu/character.ts', ['/afu/front.png', 'characterExpression'], 'character.test.ts'),
 20: ('windows/src/afu/pet.ts', ['pointer', 'click'], 'pet.test.ts'),
 21: ('windows/src-tauri/src/disari.rs', ['outside', 'test'], 'cargo.log'),
 22: ('windows/src/core/hit.ts', ['hitRect', 'ignoresClicks'], 'hit.test.ts'),
 23: ('windows/src/style.css',
      ['button:focus-visible', '.primary-button:active', '.agent-pill:hover'],
      'working-100.png'),
 24: ('windows/src/island/fsm.ts', ['hover', 'petit'], 'fsm.test.ts'),
 25: ('windows/src/island/fsm.ts', ['hidden', 'petit', 'home'], 'fsm.test.ts'),
 26: ('windows/src-tauri/src/island.rs', ['set_always_on_top(true)'], 'source_hashes.json'),
 27: ('windows/src-tauri/src/tray.rs', ['TrayIconBuilder', '"quit", "Çıkış"'], 'cargo.log'),
 28: ('windows/src-tauri/src/glide.rs', ['watch_fullscreen', 'tam_ekran_acik'], 'cargo.log'),
 29: ('windows/src/core/layout.ts', ['KART_OLCEK', 'DESIGN_W', 'DESIGN_H'], 'p8_kart_buyut.test.ts'),
 30: ('windows/src/chat/chat.ts', ['codexLogin', 'codexSend'], 'chat.test.ts'),
 31: ('windows/src/sor/sor.ts', ['sorCevapla', 'primary-button', 'sor-actions'], 'sor_ui.test.ts'),
 32: ('windows/src/sor/yerel.ts', ['niyetBul', 'sorCevapla', 'cevapUret'], 'tum_ozellik_etkilesim.test.ts'),
 33: ('windows/src/question/question.ts', ['cevapHazirla', 'sonGecerlilik', 'varsayilan'], 'question.test.ts'),
 34: ('windows/src/main.ts', ['attachFiles'], 'island_connections.test.ts'),
 35: ('scripts/afu_ajan_koprusu.py', ['ONAY_SURE = 110', 'onay_iste'], 'test_afu_ajan_koprusu.py'),
 36: ('windows/src/core/apps.ts', ['appRows', 'kurulu'], 'apps.test.ts'),
 37: ('windows/src/core/labels.ts', ['Tekrar dene', 'retryFail', 'failed'], 'labels.test.ts'),
 38: ('windows/src/views/model.ts', ['emptyState', 'retry'], 'tum_ozellik_gorev.test.ts'),
 39: ('windows/src/views/views.ts', ['retryButton', 'this.retry()'], 'arayuz.test.ts'),
 40: ('windows/src-tauri/src/bildirim.rs', ['Tekillestirici', 'muted'], 'cargo.log'),
 41: ('windows/src/views/model.ts', ['filterTasks', 'filterVisible'], 'tum_ozellik_gorev.test.ts'),
 42: ('windows/src/views/overlay.ts', ['Katman', 'Escape'], 'arayuz.test.ts'),
 43: ('windows/src/views/overlay.ts', ['Tab', 'focus'], 'arayuz.test.ts'),
 44: ('windows/src/core/labels.ts', ['UI_TR', 'UI_EN', 'setLanguage', 'uiFit'], 'q1_uzun_metin.test.ts'),
 45: ('windows/src/core/metin.ts', ['clipText', 'clipBlock', 'title'], 'q1_uzun_metin.test.ts'),
 46: ('windows/src-tauri/src/ilk_kullanim.rs', ['prepare', 'create_new(true)', 'AlreadyExists'], 'cargo.log'),
 47: ('windows/src/views/views.ts', ['ROW_LIMIT = 3', 'sor', 'more-menu'], 'sor_ui.test.ts'),
 48: ('windows/src-tauri/src/watch.rs', ['partial_publication_retries_once_and_recovers_without_restart'], 'cargo.log'),
 49: ('windows/src-tauri/src/protokol.rs', ['pub fn coz', 'ajan'], 'cargo.log'),
 50: ('windows/src-tauri/src/protokol.rs',
      ['Thinking', 'Working', 'Question', 'Finished', 'Error', 'RateLimit'],
      'protokol.test.ts'),
 51: ('windows/src-tauri/src/ipc.rs', ['CreateNamedPipeW', 'boru_adi'], 'cargo.log'),
 52: ('windows/src/core/protokol.ts', ['ajanOlaylariniDinle', 'ajan_listesi'], 'protokol.test.ts'),
 53: ('scripts/afu_ajan_koprusu.py', ['ZAMAN_ASIMI', 'onay_iste'], 'test_afu_ajan_koprusu.py'),
 54: ('windows/src-tauri/src/hook_kur.rs', ['onizle', 'uygula', 'backup_file.sync_all()'], 'cargo.log'),
 55: ('windows/src-tauri/src/ipc.rs', ['PIPE_REJECT_REMOTE_CLIENTS', 'EqualSid', 'CancelIoEx'], 'cargo.log'),
 56: ('windows/src/sistem/servis.ts', ['GitHubPanel', 'servis_panel_open'], 'servis.test.ts'),
 57: ('windows/src-tauri/src/ses.rs', ['include_bytes!', 'basladi.wav', 'hata.wav'], 'test_tum_ozellik_sozlesme.py'),
 58: ('windows/src-tauri/src/log.rs', ['maskele', '2097152', 'afunobet-ui.3.log'], 'cargo.log'),
 59: ('scripts/sahte_olay.py', ['play_bos', 'play_codex_soru', 'play_bayat'], 'test_sahte_mod.py'),
 60: ('windows/src-tauri/src/kimlik.rs', ['CredWriteW', 'CredReadW', 'write_volatile'], 'cargo.log'),
 61: ('windows/src-tauri/src/apps.rs', ['https://github.com/pirncedark/'], 'security_links.test.ts'),
 62: ('ses_deneme/afu_konus.py', ['resolve_local'], 'test_ses_paths.py'),
 63: ('windows/src/afu/pet.ts', ['PetModel', 'SEKANSLAR'], 'tum_ozellik_pet.test.ts'),
 64: ('windows/src/afu/oynatma.ts', ['kareSecimi', 'donguSuresi', 'ImageDecoder'], 'tum_ozellik_pet.test.ts'),
 65: ('studyo/animasyon_studyo.html', ['Dışa', 'eşitle'], 'test_studyo_uygula.py'),
 66: ('windows/src/afu/pet.ts', ['sarkac', 'sarkacHedef', 'sarkacUzama'], 'tum_ozellik_pet.test.ts'),
 67: ('windows/src/message/message.ts', ['BalonKuyrugu', 'balonOlustur'], 'mesaj.test.ts'),
 68: ('windows/src/views/views.ts', ['quota', 'apps', 'orkestra', 'chat'], 'tum_ozellik_gorev.test.ts'),
 69: ('windows/src/afu/pet.ts', ['sigdir', 'PET_NORMALIZE'], 'tum_ozellik_pet.test.ts'),
 70: ('windows/src/core/layout.ts', ['KART_OLCEK = 1.5', 'DESIGN_W', 'DESIGN_H'], 'p8_kart_buyut.test.ts'),
 71: ('windows/src/question/question.ts',
      ['soru-secenekler', 'soru-yazi', 'cevapHazirla'],
      'tum_ozellik_etkilesim.test.ts'),
 72: ('windows/src/message/message.ts', ['BalonKuyrugu', 'kapat()'], 'tum_ozellik_pet.test.ts'),
 73: ('windows/src/core/layout.ts', ['petBalonKutusu', 'petPencereYuksekligi'], 'pet-balon.test.ts'),
 74: ('windows/src/afu/oynatma.ts', ['donguArasi', 'kareSecimi', 'rastgeleBekleme'], 'tum_ozellik_pet.test.ts'),
 75: ('windows/src/message/notifications.ts',
      ['MessageNotifications', 'setAlwaysOnTop', 'showNotification'],
      'notifications.test.ts'),
 76: ('windows/src/message/message.ts', ['KonusanAfu', 'balonOlustur', 'temizMetin'], 'r3b1.test.ts'),
 77: ('windows/src/afu/pet.ts', ['SEKANSLAR', 'PET_OYNATMA'], 'tum_ozellik_pet.test.ts'),
 78: ('windows/src/views/model.ts', ['handoffText'], 'w3_devir.test.ts'),
 79: ('windows/src/afu/ifade.ts', ['IFADELER', 'sonrakiAralik'], 'pet-ifade.test.ts'),
 80: ('windows/src/style.css', ['tik-bildirim'], 'w2_toast_yerlesim.test.ts'),
 81: ('windows/src/chat/chat.ts', ['codexLogin', 'codexLoginCancel'], 'chat.test.ts'),
 82: ('windows/src/core/ajan_kimlik.ts', ['ajanKimlik', 'renkTonu'], 'w4_pill.test.ts'),
 83: ('windows/src-tauri/src/yaslanma.rs', ['pub fn pet_yeri'], '../../../windows/src-tauri/src/yaslanma.rs')}
